site_name: Thuya CMS
repo_name: thuya-cms 
repo_url: https://github.com/thuya-cms

theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.indexes
    - content.tooltips
  palette:
    scheme: slate
    primary: green
    accent: amber

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Welcome: index.md
  - Terminology: terminology.md
  - Development:
    - Module: development/module.md
    - Content Provider: development/content-provider.md
    - Content Definition: development/content-definition.md
    - Content Field Definition: development/content-field-definition.md
    - Controller: development/controller.md